### ISSUE TITLE
adding info

### ISSUE THREAD

**Issue by SCaryBonsai** [aquasarus/Starfield-Interactive-Smart-Slate#1]
Hi, the ADD button is greyed out so i cannot add any information. I may be missing a step but i am unsure. can you please help me sort this out?

The app is really cool btw. I hope i can get it to work.

**Comment by aquasarus** [comment]
Hello! You've cemented your position as the first issue ever posted on my project :D. I see you closed the issue, so I hope you figured it out. The `Add` button is meant to only be available when there are fauna/flora left to explore on the planet or moon. If something doesn't match up with the in-game info, let me know! Our data isn't perfect, so I'll be tweaking it as I go.

**Comment by SCaryBonsai** [comment]
Lol yeah I figured that out. I tried to delete my post but couldn't lol.

**Comment by aquasarus** [comment]
No problem! GitHub issues are meant to persist so that other people who encounter similar problems can potentially find their answers here.
