### ISSUE TITLE
Deleting something ?.

### ISSUE THREAD

**Issue by Zatopek33** [aquasarus/Starfield-Interactive-Smart-Slate#17]
Hello,

Please, if somebody make a mistake ! There is no way to delete something ?
Wtf ? It's a joke ????

**Comment by aquasarus** [comment]
@Zatopek33 The reason I didn't add a delete lifeform button is to match the additive nature of Starfield's exploration gameplay loop. I'm assuming my users' goals are to continue to explore and survey, which means fixing a mistake is as easy as editing it to a correct lifeform! Outposts, on the other hand, can be deleted for obvious reasons.

**Comment by Zatopek33** [comment]
Sorry, but i speak about mistakes from error entry from keybord for for example fauna and flora names !


Emmanuel Bruic11 rue des Piliers de Tutelle
33000 Bordeaux

 

    Le mardi 2 janvier 2024 à 19:13:08 UTC+1, Jason ***@***.***> a écrit :  
 
 


@Zatopek33 The reason I didn't add a delete lifeform button is to match the additive nature of Starfield's exploration gameplay loop. I'm assuming my users' goals are to continue to explore and survey, which means fixing a mistake is as easy as editing it to a correct lifeform! Outposts, on the other hand, can be deleted for obvious reasons.

**Comment by Zatopek33** [comment]
finally if an error typying occured, there is no way !


Emmanuel Bruic11 rue des Piliers de Tutelle
33000 Bordeaux

 

    Le mardi 2 janvier 2024 à 19:13:08 UTC+1, Jason ***@***.***> a écrit :  
 
 


@Zatopek33 The reason I didn't add a delete lifeform button is to match the additive nature of Starfield's exploration gameplay loop. I'm assuming my users' goals are to continue to explore and survey, which means fixing a mistake is as easy as editing it to a correct lifeform! Outposts, on the other hand, can be deleted for obvious reasons.

**Comment by aquasarus** [comment]
I see. If you entered something incorrectly, you can always edit fauna/flora details by clicking the "Edit" button on the top right corner of the **Entity Overview**. Let me know if that helps!

**Comment by Zatopek33** [comment]
You have to update your project in this way, give your user some flexibility !

**Comment by aquasarus** [comment]
If editing is not enough for you, the next update will include fauna/flora deletion :). This is because I will be adding an option to unlock the existing total fauna/flora counts for planets with life, since some people are already modding the game to add more aliens!

**Comment by Zatopek33** [comment]
Yes ! You do a great job finally thanks to you :) Editing help me, i did'nt see this way !

**Comment by Zatopek33** [comment]
But yes make a user to delete someting if someting is wrong, this will be great ! Thanks you again, great job !

**Comment by Zatopek33** [comment]
An other thing, planet is submited to 100% exploration, i do not see the resources planet (iron or aluminium and so on ...) to reach this exploration, but outposts. Outpost are not a way to reach 100% planet exploration.


Emmanuel Bruic11 rue des Piliers de Tutelle
33000 Bordeaux

 

    Le mardi 2 janvier 2024 à 19:18:32 UTC+1, Emmanuel Bruic ***@***.***> a écrit :  
 
 finally if an error typying occured, there is no way !


Emmanuel Bruic11 rue des Piliers de Tutelle
33000 Bordeaux

 

    Le mardi 2 janvier 2024 à 19:13:08 UTC+1, Jason ***@***.***> a écrit :  
 
 


@Zatopek33 The reason I didn't add a delete lifeform button is to match the additive nature of Starfield's exploration gameplay loop. I'm assuming my users' goals are to continue to explore and survey, which means fixing a mistake is as easy as editing it to a correct lifeform! Outposts, on the other hand, can be deleted for obvious reasons.

**Comment by aquasarus** [comment]
Hmm I'm not sure what you mean. This app currently only represents exploration progress using fauna/flora. Resources and outposts are not considered.

**Comment by Zatopek33** [comment]
yes i understand.


Emmanuel Bruic11 rue des Piliers de Tutelle
33000 Bordeaux

 

    Le mardi 2 janvier 2024 à 19:51:53 UTC+1, Jason ***@***.***> a écrit :  
 
 


Hmm I'm not sure what you mean. This app currently only represents exploration progress using fauna/flora. Resources and outposts are not considered.

**Comment by aquasarus** [comment]
@Zatopek33 FYI the next release is coming soon, and I've added the ability to delete fauna/flora :D

**Comment by aquasarus** [comment]
Added in [v1.3.0](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/discussions/20).
