### ISSUE TITLE
Unable to add fauna in Syrma IV

### ISSUE THREAD

**Issue by MaamuT** [aquasarus/Starfield-Interactive-Smart-Slate#19]
Impossible to add a plant species, the software blocks two even though there are three.

Planet Syrma IV on Syrma system.

**Comment by aquasarus** [comment]
Good catch! Let me fix this. The next version will also allow you to unlock it entirely, since some mods may be adding more aliens.

**Comment by aquasarus** [comment]
Fixed in [v1.3.0](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/discussions/20)!
