### ISSUE TITLE
Lantana III, Échinoserre not Echinoserre

### ISSUE THREAD

**Issue by MaamuT** [aquasarus/Starfield-Interactive-Smart-Slate#21]
In Lantana III

Échinoserre (note accent on the E, Alt+0201) not Echinoserre

**Comment by aquasarus** [comment]
Hey! Nice to see that you're still playing and using the app :D. I've put the changes into [a small patch](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/releases). Let me know if it works!

**Comment by MaamuT** [comment]
I'm still on my 100% challenge, and now I'm at 753 planets completely scanned.

I'm NG+10, I have almost all the mugs, all the caps, all the snow globes, visited all the vestiges of the old earth and other things too (5 red lines out of 29, 5 books for Mitch Benjamin on 30) etc.

**Comment by MaamuT** [comment]
And yes, ISS are my companion ;)

**Comment by aquasarus** [comment]
Haha that's amazing!

**Comment by MaamuT** [comment]
> Hey! Nice to see that you're still playing and using the app :D. I've put the changes into [a small patch](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/releases). Let me know if it works!

It's work nicely, congrats to the reactivity ;)

**Comment by aquasarus** [comment]
Thanks! I'll go ahead and close the issues then.
