### ISSUE TITLE
Error in 1.3.2, update alert

### ISSUE THREAD

**Issue by MaamuT** [aquasarus/Starfield-Interactive-Smart-Slate#24]
when we launch 1.3.2, a message announces that we are still in 1.3.1

**Comment by aquasarus** [comment]
@MaamuT You may have accidentally launched an older version of the app. Be sure to download the [latest release](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/releases) and delete the other ones!

**Comment by MaamuT** [comment]
Yes, I have the latest version, I even have the option to deactivate the fauna/flora limit, so it is indeed the latest

**Comment by aquasarus** [comment]
The option to unlock the limit was actually added in 1.3.0. Can you check the "About / Help" tab to see which version the app is?

![image](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/assets/1495089/af10920b-668f-4def-8383-e4f5f1a97d8e)

**Comment by MaamuT** [comment]
Ok, I hadn't seen the fauna/flora option.

I just started the installation again, deleted my current version, downloaded the zip, reinstalled, and I still get the message telling me I'm not up to date.


![image](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/assets/5188838/a8572715-784d-4bcd-9ddf-bc53c56b8bda)

**Comment by aquasarus** [comment]
Ahh you're right. I must've uploaded the wrong version. I just changed it so try downloading 1.3.2 again and see if it works :).

**Comment by MaamuT** [comment]
I confirm, it's good now, you can close the report ;)

**Comment by aquasarus** [comment]
Awesome. Thanks!
