### ISSUE TITLE
Can't access app top bar 

### ISSUE THREAD

**Issue by Aldhari** [aquasarus/Starfield-Interactive-Smart-Slate#4]
Under w10, opening the app will not center the window, and can't be moved because of inaccessible top bar

![image](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/assets/115947362/21556fb4-9427-4e29-bb94-f4fc1f775c57)

https://imgur.com/a/R0j0eXh

**Comment by aquasarus** [comment]
Hmm you're right. I need to resize the window when the default size is too big for the screen resolution. I'll work on a fix, but in the meantime, you can resolve it on your end with `WinKey + Up`, which is the system shortcut to maximize a window.

**Comment by aquasarus** [comment]
@Aldhari I just added a fix, but I'm planning to group it into the next release. If the `WinKey + Up` shortcut is not working for you, let me know and I'll get you a personal build :).

**Comment by aquasarus** [comment]
Fixed in v1.2.0!
