### ISSUE TITLE
Can't access app top bar 

### ISSUE THREAD

**Issue by Aldhari** [aquasarus/Starfield-Interactive-Smart-Slate#5]
Under w10, opening the app will not center the window, and can't be moved because of inaccessible top bar

![image](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/assets/115947362/21556fb4-9427-4e29-bb94-f4fc1f775c57)

**Comment by aquasarus** [comment]
Duplicate of https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/issues/4
