### ISSUE TITLE
Limited data shown, limited interactivity

### ISSUE THREAD

**Issue by laurac8r** [aquasarus/Starfield-Interactive-Smart-Slate#8]
------------------

## Expected Behavior

Showing data, interactivity

## Current Behavior

1. No secondary planetary data showing, limited interactivity
    <details><summary>Screenshot</summary>
    <p>
    
    ![Planetary Data](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/assets/23003243/602c979c-1791-4dbd-ae56-5e05a10ece70)
    
    </p>
    </details>

1. No secondary inorganic data showing, limited interactivity

    <details><summary>Screenshot</summary>
    <p>
    
    ![Inorganic Data](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/assets/23003243/82bbd0fa-9846-45cc-b9a8-9efee06e8037)
    
    </p>
    </details> 

1. No organic data showing, limited interactivity

    <details><summary>Screenshot</summary>
    <p>
    
    ![Organic Data](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/assets/23003243/ac0189b1-1a5c-4ec8-a2b9-7b0baed966a9)
    

## Possible Solution

- [ ] SQL server driver issues
- [ ] Schema divergence code vs DB
- [ ] Some OS dependency

## Steps to Reproduce

1. Install
2. Open app
3. Click through different views

## Context (Environment)

The result and impact is the app has limited usability.

</p>
</details> 

<details><summary>Computer Configuration</summary>
<p>

------------------
System Information
------------------

| Operating System                           | Processor                                                                  | Memory   |
|--------------------------------------------|----------------------------------------------------------------------------|----------|
| Windows 11 Home 64-bit (10.0, Build 22621) | 11th Gen Intel(R) Core<sup>TM</sup> i7-11800H @ 2.30GHz (16 CPUs), ~2.3GHz | 64GB RAM |

----------------
Display Settings
----------------

| DirectX Version | User DPI Setting      | System DPI Setting   | 
|-----------------|-----------------------|----------------------|
| DirectX 12      | 120 DPI (125 percent) | 96 DPI (100 percent) |

| Card name (Integrated) | Display Memory | Current Mode                 |
|------------------------|----------------|------------------------------|
| Intel(R) UHD Graphics  | 32 GB          | 1920 x 1080 (32 bit) (144Hz) |

| Card name (Dedicated)              | Display Memory | Current Mode                |
|------------------------------------|----------------|-----------------------------|
| NVIDIA GeForce RTX 3060 Laptop GPU | 38 GB          | 1680 x 1050 (32 bit) (59Hz) |

</p>
</details> 

## Detailed Description

- [ ] Logging tab to debug
- [ ] Unit and integration testing for features

## Possible Implementation

- [ ] Web UI interface (for example, frontend Vue.js + backend Node.js)
- [ ] Release dataset behind DB to, say, Kaggle.com or HuggingFace.com

------------------

**Comment by aquasarus** [comment]
Hi there. Thanks for providing such a detailed issue description! Unfortunately, I'm really not sure what you're talking about. This app is built as an explorer's tool, which means you're meant to add your own data. Solar systems won't appear until you've discovered them, and resource searches won't have results until you've added relevant data. Perhaps you can check out the [gifs in the README file](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate#discover-solar-systems) for a demo?

**Comment by laurac8r** [comment]
aquasarus hi :) so for example the Celestial Bodies table is present in the DB and filled out but does not appear in the SISS ui

![image](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/assets/23003243/3ec6797c-d2b1-44e2-93f6-619b5df3ad3e)

![image](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/assets/23003243/7b4f0a36-d101-4746-b708-5c6a07ed85c2)

**Comment by laurac8r** [comment]
sorry yes you are right although a tooltip or guide would be a nice future feature :)
