### ISSUE TITLE
French Translation Work-In-Progress

### ISSUE THREAD

**Issue by birilo** [aquasarus/Starfield-Interactive-Smart-Slate#9]
Hello ! Thanks a lot for your app ! Now I can explore and writing down all the discover I made ! I feel like more an explorer with this tool.

But I was able to spot an oversight: Guniibuu System, Planet Guniibuu II, one plant is missing, there are 8 different ones on this planet, only 7 can be listed right now on the ISS.

However, would it be possible to add an option for proposals to add this kind of oversight directly to the ISS?

And do you need help to translate the names of fauna, flora and crops ? I'm french, my game is in french, so I would like to add my discovery in that language, but there is no auto complete and it's not really practical if I want to look for something in the ISS.

Thanks again, great work.

See you space.

Birilo

**Comment by aquasarus** [comment]
Thank you for your kind words!

1. Good catch on Guniibuu. This has already been reported and fixed in the next major release (v1.3 with Outpost Tracking!). It will probably be ready in a few days :). After that, I will start shipping smaller updates to make sure things are fixed more quickly.
2. Unfortunately, to allow ISS to directly report issues will require me to link up your GitHub account to the app, which is not really worth it at the moment. I suspect most ISS users won't even have a GitHub account to begin with. The easiest way in ISS right now is to go to the **About** tab and click **Submit Bug Reports and Suggestions**, which will link you to the issues page. Feel free to open as many issues as you see fit!
3. This is so exciting to hear! I knew that localization (i.e. new languages) would be required if a lot of people started using the app, but I wasn't sure if anyone would even be interested in this. So I started simple with just English. Translating the app's UI to French should be easy, but including auto-complete for Fauna/Flora in French will require the app to have a comprehensive list of every Fauna/Flora's French name in the game. It's likely not feasible for you to go and find every lifeform in your game to compile this list, but there may be resources online already available. Do you think you can look around to see if there is a French wiki with all Faunas and Floras cataloged? Thank you in advance!

**Comment by aquasarus** [comment]
This is amazing. After v1.2, I'm gonna cross-reference the wiki you linked with my existing data. If everything checks out, I'll plug it in. At that point, I might as well provide an entire French version of the app. If I send you a list of all English UI texts in the app, would you mind translating them for me?

**Comment by MaamuT** [comment]
Hi,

I'm French and I'm hot for a French version too ;)

**Comment by aquasarus** [comment]
@MaamuT Gotcha! I apologize for the delays. I had intended to start working on localization immediately after v1.2, but a new contributor joined this team (he's working on an [awesome UI upgrade](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/discussions/11)!) and I need to first clean up the project a bit to allow for faster collaboration. I'll be jumping right back into planned improvements after that :).

**Comment by MaamuT** [comment]
Yes, I understood that the project was taking a new turn and I am the first to be very excited, looking forward to the sequel.

Take the time you need, I'm not in a hurry, I even intend to play the game 100%, so I have time ahead of me, and then, as long as the new version keeps my data already informed, no problem for me ;)

**Comment by aquasarus** [comment]
Good luck and enjoy the journey to 100% :D. And yes, new app versions will always be backwards compatible.

**Comment by MaamuT** [comment]
I have other suggestions, I will take advantage of this thread to offer them.

Possibility of deleting an incorrect entry, if I make a mistake by adding an animal or floral species, or an outpost, it would be nice if I could delete it.

Ability to sort the system list by name.

Possibility of folding/unfolding the system to save space.

A global search engine allowing you to search for materials, resources or outposts by name.

**Comment by aquasarus** [comment]
@MaamuT the Issues page is actually meant for reporting bugs and other problems. Could you post your suggestions to [Discussions > Ideas > New Discussion](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/discussions/new?category=ideas)? I will reply to them there :).

**Comment by aquasarus** [comment]
@birilo @MaamuT just wanted to let you guys know that I've now started working on **Starfield ISS v1.3** after real life forced me to step away for a while. I've found 218 fauna names and 158 flora names from [https://starfield-wiki.com](https://starfield-wiki.com), but in my current DB I have 642 fauna names and 159 flora names in English. I need your help to improve the French list to be more comprehensive!

Part of the reason there are so many fauna names in English is due to all the different modifications. e.g. There is Hunting Glider, Swarming Glider, Herding Glider Grazer, etc. Do you have similar stuff in the French version? Or do the 218 names in that wiki actually include everything available?

**Comment by MaamuT** [comment]
Hi,

You could provide us with a text file of the database, in table form, with for each line, the EN version and the FR version, it will be easier to understand.

I think you need to count the variants of each species, but to confirm and refine the translation, I need a comparison.

**Comment by aquasarus** [comment]
@MaamuT unfortunately I don't know which English faunas the French names correspond to. Maybe we can use Jemison as an example? Here are all the English faunas I've scanned from Jemison (Alpha Centauri):

- Pack Coralbug
- Apex Parrothawk
- Flocking Seabat Geophage
- Hunting Tuskfrog
- Carasnail Scavenger
- Herding Cutterhead Herbivore
- Herding Reefwalker Scavenger
- Beetle Grazer
- Apex Crocodaunt

Can you show me what they are in the French version for Jemison?

**Comment by aquasarus** [comment]
> Sorry for the delay, I have somewhat complicated work schedules.

No worries at all! We're all contributing to this for free :D. 

And thanks a lot for breaking it down. This is very useful information. It seems like the list from that wiki contains only the species names. I'm going to process the English name list to see if I can match each one, and then use that to output every group behavior and diet like you described. Once we figure out the translation for all modifiers, I can use them to convert the entire English names list to French. Stay tuned!

**Comment by aquasarus** [comment]
@MaamuT so far I've found the following modifiers that need translation:

- Filterer
- Grazer
- Schooling
- Shoaling
- Stalker
- Swarming

I'm sorting through some of the unique fauna names in the English list to see if the French species list from the wiki includes everything. I'll update you when I have more time to work on this.

**Comment by MaamuT** [comment]
Yep

Grazer => Brouteur
Filterer => Filtreur

Could you tell me on which planets to find the others?

**Comment by aquasarus** [comment]
I found some examples for you to look up:
- **Schooling** Bladehead Grazer (fish) in **Polvo, Valo**
- **Shoaling** Finback Scavenger (fish) in **Guniibuu VI-b, Guniibuu**
- Hunting Angler **Stalker** in **Guniibuu II, Guniibuu**
- **Swarming** Sunflower in **Montara Luna, Cheyenne**

**Comment by MaamuT** [comment]
Hi,

Schooling Bladehead Grazer => [Grégaire] Lamette [Brouteur]
Shoaling Finback Scavenger => [Banc] Ailette [Charogne]
Hunting Angler Stalker => [Chasse] Lophius [Dépeceur]
Swarming Sunflower => [Nuée] Tournesol

Schooling => Grégaire
Shoaling => Banc
Stalker => Dépeceur
Swarming => Nuée

Addition :
Planet :
The Pup => Le Rejeton

**Comment by aquasarus** [comment]
@MaamuT Awesome! I have a question for you. Do the brackets show up in-game as well? For example, when you scan the Schooling Bladehead Grazer in Starfield, does it say "[Grégaire] Lamette [Brouteur]" or just "Grégaire Lamette Brouteur"? And if it shows the brackets, do you also use them yourself in Starfield ISS? I want to know if I should include the brackets in the French version of auto-complete.

**Comment by MaamuT** [comment]
Yes, the brackets are clearly displayed in-game.

**Comment by aquasarus** [comment]
Okay cool. I'll make sure to include the brackets in auto-complete.

**Comment by aquasarus** [comment]
@MaamuT @birilo okay I've done some work to match up what I can with the French wiki. I still have ~100 fauna names that I couldn't match. Maybe you can help me out?

[Here are my current matches](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/blob/main/ImportTools/french_translation.py#L79). See if I got any wrong!
[Here are the English fauna names](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/blob/main/Localization/fr/english_untranslated_fauna_names.txt) that haven't been matched.
[Here are the French fauna names](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/blob/main/Localization/fr/french_fauna_names.txt) from the wiki that are still available for matching.

**Comment by MaamuT** [comment]
Ok, I downloaded the files, I'll look at it this week, as soon as my job gives me some time ;)

**Comment by aquasarus** [comment]
@MaamuT thank you and good luck!

**Comment by aquasarus** [comment]
FYI by knowing the translation of all modifiers, our current English -> French matching will let our script translate about half of all faunas in Starfield:
![image](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/assets/1495089/25ff89b5-e7ee-434b-b51f-f8df252be19a)

**Comment by MaamuT** [comment]
Hi,

Sorry for the delay, I had to visit each planet to find the names ;)

In french_translation.py :

`known_special_names = {
    'Red Mile Mauler': 'Boxeur de la ligne rouge',
    'Apex Dust Devil Exorunner': '[Alpha] Rôdeur des sables exocoureur',
    'Rainbow Agnathan': 'Agnathan arc-en-ciel',
    'Pack Prong Wing Seabat': '[Meute] Aile dentue noctule', # Pack seems to be the only modifier here, with Prong Wing Seabat as the species name
    'Grazing Ensifer': 'Ensifer paissant',
    'Greater Jaffa Lizard': 'Grand lézard Jaffa',
    'Lesser Jaffa Lizard': 'Petit lézard Jaffa',
    'Flying Leech': 'Sangsue volante',
    'Elk Crangon': 'Orignal de Crangon',
    'Crawling Eurypterid': 'Euryptéride rampant',
    'Crag Sprinter': 'Sprinteur des falaises',
    'Baleen Rotifer': 'Rotifère baleine',
    'Terrormorph': 'Horrimorphe',

    'Cataxi Hunter': 'Chasseur Cataxi',
    'Cataxi Warrior': 'Guerrier Cataxi',
    'Grylloba Hunter': 'Chasseur Grylloba',
}`

**Comment by aquasarus** [comment]
@MaamuT awesome! I've added your contribution to [the code base](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/commit/3b20b879eb6cc978377579c994538872ce5234b0), which brings our French translated fauna to 350. Now we just have to match up the rest of the species names [in here](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/blob/main/Localization/fr/english_untranslated_fauna_names.txt) with [what the French wiki provides](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/blob/main/Localization/fr/french_fauna_names.txt).

**Comment by MaamuT** [comment]
I am delighted.

Don't hesitate if you have any other questions, I'll look for the answer in-game.

**Comment by MaamuT** [comment]
Commit sent, I only translated the terms coming from planets already visited, some are still missing.

If you know the planets involved, I will visit them to finish the translation.

**Comment by aquasarus** [comment]
@MaamuT commits actually stay on your local PC until you push them to a repo! If you want me to see your changes, you'll have to fork this repository and push it there. Also, you can find the planets to visit in [this spreadsheet](https://docs.google.com/spreadsheets/d/1seE2vzP_8Whs43C-6CXpoHPyJMFGoUH4TkSzeJqMHm4/edit#gid=1203680207). Feel free to ignore the modifiers, since we only need to translate the species names now.

**Comment by MaamuT** [comment]
Ok, I have a synchronization problem, the push doesn't want to go :/

**Comment by aquasarus** [comment]
Thanks! Posting it here is totally fine. (If you just cloned this repo, it won't let you push because you don't have permission to manage this repository.)

**Comment by MaamuT** [comment]
Indeed, I threw the push without thinking about the permissions, I'm a little stupid on this one :/

Planets currently visiting, I have quite a way to go to finish the file, but I think I'll get there today.

**Comment by MaamuT** [comment]
I found two plant species with the same name but with different resources on Bardeen III, but counted by the game as one: the Leafy morningstar (Leafy morningstar => Ombellium feuillue, one with Toxin and one with Sealent).

The translation of english_untranslated_fauna_name.txt :

Brainsprout => Encéphalobulbe
Horsamander => Chevalamandre
Bonefrill => Huître-os
Clawback => Echinoserre
Glowhands => Luisemain
Cagebrain => Carcéphale
Clickbeetle => Caraboclic
Leafstrider => Phyliogerris
Shardhopper => Saute-fragment
Tongueface => Languos
Stonewalker => Lithomarcheur
Cutterhead => Coupereux
Grub => Pupe
Rockhound => Petraqueur
Toadface => Batraface
Grabber => Pince
Boneback => Echinos
Paddlefish => Poisson-pale
Finback => Ailette
Spaceroach => Spafard
Canard => Canard
Brightcage => Luise-cage
Hornface => Cornicéphale
Saturnine => Saturnin
Seabat => Noctule-marine
Stingray => Raie manta
Windbag => Sac d'air
Mothwing => Aile de Sphinx
Noid => Noïde
Sailgator => Naviligator
Vectorback => Glisse-dos
Seahag => Vieille marine
Brainblimp => Macrocortex
Marnokk => Marnokk
Scarab => Scarabée
Shellephant => Coquéléphant
Snuffler => Renifleur
Tubecrawler => Veratube
Mayfly => Ephémère
Landshark => Terrosquale
Silverfish => Lépisme
Skullface => Crânegueule
Twistfin => Révoloire
Maggotmaw => Beclarve
Bladehead => Lamette
Sawhead => Tête de scie
Flapwheel => Claque-roue
Cranehopper => Criquet-grue
Earback => Oreillon
Lionbear => Leonursa
Sporeback => Sporéchine
Triantler => Tribois
Glowback => Luciole
Gossamer => Fil de vierge
Boneglider => Ostéoplaneur
Dragonfly => Libellule
Lacraia => Lacraia
Longneck => Grand-cou
Loxodont => Loxodonta
Shieldshell => Boucliarapace
Wiggler => Anchet
Wobbleback => Domollis
Foxbat => Chauve-renard
Nailtail => Queue clouée
Tentabeard => Tentabarbe
Trapmaw => Cage-gueule
Kreet => (Kreet grazer => Herbivore de Kreet, Kreet stalker => Traqueur de Kreet)
Stingback => Dardos
Sunfish => Poisson-lune
Twintail => Bifide
Tubule => Tubule
Twingrub => Gémelarve
Buzzrunner => Buzzrunner
Dropsalm => Dropsalm
Fingerface => Digicéphale
Fleshleaf => Phylocarnius
Cobalt => Cobalt
Eyespine => Irispinal
Plateskin => Metalyderme
Roundface => Rotonde
Shroomhead => Champi
Grylloba => Grylloba
Fluke => Douve
Kelpstrider => Algoculteur
Leecher => Calovorus
Reefwalker => Marcherécif
Scoopback => Écope
Stoneback => Lithoverso
Twigwalker => Branchipode
Hornwing => Cornoptère
Bonecrest => Ostéocrète
Hookneck => Nucroc
Jellyfin => Méduse à palme
Lesser => (Lesser => petit (little, small), Lesser Silverfish => Petit lépisme)
Morningstar => Ombellium feuillue
Mossgnath => Mossgnath
Bearclaw => Griffe-ours
Bladepack => Échinolame
Featherfin => Poisson-plume
Shroombobber => Mycoflotteur
Siren => Sirène

**Comment by aquasarus** [comment]
@MaamuT you're so fast! And good catch on the special Kreet translations. Here is the next step:

I have a few of my own species translations that I'm not confident about. Can you survey them in-game and check if I got them right?
```'Thornback' : 'Échinoserre',
'Whaleshark': 'Requin-baleine',
'Sharkwhale': 'Baleine-requin',
'Nautilus' : 'Nautilus',
'Nautiloos': 'Nautile',
```

**Comment by MaamuT** [comment]
All the names on the list come from the game, I found them by visiting the planets and writing them down.

**Comment by MaamuT** [comment]
Just MaamuT it's fine ;)

I'll look at it during the week, as soon as I have time, Thursday I think.

**Comment by MaamuT** [comment]
It's ok for me, I don't see anything to say about this list.

**Comment by aquasarus** [comment]
French autocomplete has been added in [v1.3.0](https://github.com/aquasarus/Starfield-Interactive-Smart-Slate/discussions/20)! Full localization is still on the table but will probably come much later. We can discuss it when I have time to come back to it.
